version: 2.1

jobs:
  automated-api-tests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Postman CLI
          command: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - run:
          name: Login using your API key
          command: postman login --with-api-key PMAK-64d75fa464a00400381c7f5c-b9662e70bc39053737a958fbcea120cd7b
      - run: |
            postman collection run "postman/collections/Pets test.json" --integration-id "146094-${CIRCLE_WORKFLOW_JOB_ID}"

workflows:
  version: 2
  automated-api-tests:
    jobs:
      - automated-api-tests
